title: "reflow"

description: "Resizing images by reflowing their pixels into new image dimensions"

# Build settings
markdown: kramdown

exclude: [
    "documentation",
    "node_modules",
    "process_data",
    "server",
    "src",
    "webpack.config.js"
]